mkdir build
cd build




%CXX% --version
clang-cl --version
@REM cmake -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
@REM       -DCMAKE_INSTALL_LIBDIR=%LIBRARY_LIB% ^
@REM       -DCMAKE_CXX_COMPILER=clang-cl ^
@REM       -DCMAKE_C_COMPILER=clang-cl ^
@REM       -DCMAKE_CXX_STANDARD_LIBRARIES=-lxml2 ^
@REM       -DWITH_SWIG=OFF ^
@REM       -DLIBXML_LIBRARY=%LIBRARY_LIB% ^
@REM       -DLIBXML_INCLUDE_DIR=%LIBRARY_INC%/libxml2 ^
@REM       -DENABLE_COMP=ON ^
@REM       -DENABLE_FBC=ON ^
@REM       -DENABLE_GROUPS=ON ^
@REM       -DENABLE_LAYOUT=ON ^
@REM       -DENABLE_MULTI=ON ^
@REM       -DENABLE_QUAL=ON ^
@REM       -DENABLE_RENDER=ON ^
@REM       -DENABLE_DISTRIB=ON ^
@REM       %SRC_DIR%
@REM make
@REM make install
